apps/accounts/urls.py
from django.urls import path

from .views import LoginView, GetUser

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('get/', GetUser.as_view(), name='get_user'),
]

apps/technical_test/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('business/add/', views.AddBusinessView().as_view(), name='add_business'),
    path('business/list/', views.ListBusinessView.as_view(), name='list_business'),

    path('departament/add/', views.AddDepartamentView().as_view(), name='add_departament'),
    path('departament/list/<int:pk>/', views.ListDepartamentView.as_view(), name='list_departament'),

    path('employee/<int:pk>/', views.GetEmployeeView().as_view(), name='edit_employee'),
    path('employee/add/', views.AddEmployeeView().as_view(), name='add_employee'),
    path('employee/edit/<int:pk>/', views.UpdateEmployeeView().as_view(), name='edit_employee'),
    path('employee/delete/<int:pk>/', views.DeleteEmployee().as_view(), name='edit_employee'),
    path('employee/list/<int:business>/<int:departament>/<str:employee>/',
         views.ListEmployeeView().as_view(), name='edit_employee'),
]

src/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.web.urls', 'web'), namespace='web')),
    path('test/', include(('apps.technical_test.urls', 'test'), namespace='test')),
    path('accounts/', include(('apps.accounts.urls', 'accounts'), namespace='accounts')),
]

apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

from apps.technical_test.models import Business, Departament
from .config import GENDER_CHOICES


class UserManager(BaseUserManager):

    def create_user(self, email, password=None):

        if email is None:
            raise TypeError('Email Requerido')

        user = self.model(email=email)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password):

        if password is None:
            raise TypeError('Se requiere Contraseña')

        user = self.create_user(email, password)
        user.is_staff = True
        user.is_superuser = True
        user.save()
        return user


class User(PermissionsMixin, AbstractBaseUser):
    business = models.ForeignKey(Business, on_delete=models.CASCADE, related_name='user', null=True)
    departament = models.ForeignKey(Departament, on_delete=models.CASCADE, related_name='user', null=True)
    email = models.EmailField(verbose_name='Correo Electrónico', null=False, blank=False, unique=True)
    is_active = models.BooleanField(default=True)
    is_administrator = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()

    def __str__(self):
        return f'{self.pk}: {self.email} -> {self.is_administrator}({self.is_active})'

    class Meta:
        ordering = ['pk']
        verbose_name = 'Usuario'
        verbose_name_plural = 'Listado de Usuarios'


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    name = models.CharField(verbose_name='Nombre (s)', null=False, blank=False, max_length=60)
    paternal_surname = models.CharField(
        verbose_name='Apellido Paterno', null=False, blank=False, max_length=60)
    maternal_surname = models.CharField(
        verbose_name='Apellido Materno', null=False, blank=False, max_length=60)
    birthday = models.DateTimeField(verbose_name='Fecha de Ingreso', null=False, blank=False)
    gender = models.CharField(
        verbose_name='Género', choices=GENDER_CHOICES, null=True, blank=True, max_length=10)
    phone = models.CharField(verbose_name='Número de Teléfono', null=True, blank=True, max_length=10)
    cell_phone = models.CharField(verbose_name='Número de Celular', null=True, blank=True, max_length=10)
    date_admission = models.DateTimeField(verbose_name='Fecha de Ingreso', auto_now_add=True)

    def __str__(self):
        return f'{self.pk}: {self.name} - {self.user.email}'

    def _get_full_name(self):
        return f'{self.name} {self.paternal_surname} {self.maternal_surname}'

    class Meta:
        ordering = ['pk']
        verbose_name = 'Perfil de Usuario'
        verbose_name_plural = 'Listado de Perfiles'

apps/accounts/views.py
from rest_framework import generics, status
from rest_framework.response import Response
from knox.models import AuthToken
from .serializers import UserSerializer, LoginSerializer


class LoginView(generics.GenericAPIView):
    serializer_class = LoginSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)

        if serializer.is_valid():
            user = serializer.get_user(serializer.data.get('email'))
            _, token = AuthToken.objects.create(user)
            return Response({
                "user": UserSerializer(user, context=self.get_serializer_context()).data,
                "token": token
            })

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class GetUser(generics.RetrieveAPIView):
    serializer_class = UserSerializer

    def get_object(self):
        return self.request.user

    def retrieve(self, request, *args, **kwargs):
        user = self.get_object()
        _, token = AuthToken.objects.create(user)
        return Response({
            "user": UserSerializer(user, context=self.get_serializer_context()).data,
            "token": token
        })

apps/accounts/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">

    <title>{% block title %}{% endblock title %}</title>

    <link rel="shortcut icon" href="{% static 'images/buho.jpeg' %}" />
    <link rel="stylesheet" href="{% static 'vendor/css/bootstrap.min.css' %}">
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/menu.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">

</head>

<body>
<div class="wrapper d-flex align-items-stretch ">
    <nav id="sidebar">
        <div class="custom-menu">
            <button type="button" id="sidebarCollapse" class="btn btn-primary">
                <i class="fa fa-bars"></i>
                <span class="sr-only">Toggle Menu</span>
	        </button>
        </div>

        <div class="p-4 pt-5">
            <h1><a href="index.html" class="logo">Splash</a></h1>
            <ul class="list-unstyled components mb-5">
                <li class="active">
                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false"
                       class="dropdown-toggle">Empresas</a>
                    <ul class="collapse list-unstyled" id="homeSubmenu">
                        <li>
                            <a href="{% url 'test:add_business' %}">Registrar Empresa</a>
                        </li>
                        <li>
                            <a href="{% url 'test:list_business' %}">Listar Empresas</a>
                        </li>
                    </ul>
	            </li>
	            <li>
                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false"
                        class="dropdown-toggle">Departamentos</a>
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li>
                            <a href="{% url 'test:add_departament' %}">Registrar Departamentos</a>
                        </li>
                        <li>
                            <a href="{% url 'test:list_departament' %}">Listar Departamentos</a>
                        </li>
                    </ul>
	            </li>

	        </ul>

        </div>
    </nav>

        <!-- Page Content  -->
    <main id="content" class="p-4 p-md-5 pt-5">
        {% block page %}{% endblock page %}
    </main>
</div>
</body>

    <script src="{% static 'vendor/js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'vendor/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/index.js' %}"></script>

</html>